"""`engram brain` — per-agent scoped memory ("mini brains").

Each brain is a self-contained directory under ``~/.engram/brains/<name>`` with
its own DB, config, telemetry, and a launcher that scopes every ``engram``
command to that brain. Isolation is the point: a specialized agent's recall and
guard fire on ITS domain, not on a global pool of unrelated projects (which is
exactly what dilutes reuse). Generalizes the hand-rolled ``./bin/brain`` pattern
into a first-class command.
"""

from __future__ import annotations

import os
import re
import shutil
import stat
import sys

from ...database import get_connection, init_db
from ..fmt import fmt_bold, fmt_dim, fmt_header

_NAME_RE = re.compile(r"^[A-Za-z0-9._-]+$")

_LAUNCHER_TEMPLATE = """#!/bin/sh
# Engram brain launcher for '{name}'. Scopes every command to this brain's
# memory by pinning ENGRAM_DB_PATH. Generated by `engram brain new`.
export ENGRAM_DB_PATH="{db}"
exec {engram} "$@"
"""


def brains_root() -> str:
    return os.path.join(os.path.expanduser("~"), ".engram", "brains")


def _brain_dir(name: str) -> str:
    return os.path.join(brains_root(), name)


def _brain_db(name: str) -> str:
    return os.path.join(_brain_dir(name), "memory.db")


def _resolve_engram_bin() -> str:
    """Absolute path to the engram entry point, for the launcher's `exec`."""
    found = shutil.which("engram")
    if found:
        return found
    argv0 = os.path.abspath(sys.argv[0])
    if os.path.basename(argv0).startswith("engram"):
        return argv0
    # Dev fallback: run the module through the current interpreter.
    return f"{sys.executable} -m src.cli"


def cmd_brain_new(args):
    name = args.name
    if not _NAME_RE.match(name):
        print("Brain name must be alphanumeric (plus . _ -).")
        sys.exit(1)
    bdir = _brain_dir(name)
    if os.path.exists(bdir):
        print(f"Brain '{name}' already exists at {bdir}.")
        sys.exit(1)

    os.makedirs(bdir, exist_ok=True)
    db = _brain_db(name)
    init_db(db)

    if getattr(args, "seed", False):
        from ...seed import seed_database

        prev = os.environ.get("ENGRAM_DB_PATH")
        os.environ["ENGRAM_DB_PATH"] = db
        try:
            seed_database(db_path=db)
        finally:
            if prev is None:
                os.environ.pop("ENGRAM_DB_PATH", None)
            else:
                os.environ["ENGRAM_DB_PATH"] = prev

    launcher = os.path.join(bdir, "brain")
    with open(launcher, "w", encoding="utf-8") as f:
        f.write(_LAUNCHER_TEMPLATE.format(name=name, db=db, engram=_resolve_engram_bin()))
    os.chmod(launcher, os.stat(launcher).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    print(fmt_header(f"✓ Brain '{name}' created"))
    print(f"  Dir: {fmt_dim(bdir)}")
    print(f"  DB:  {fmt_dim(db)}")
    print()
    print(fmt_bold("Use it (every command scoped to this brain):"))
    print(f"  {launcher} search \"...\"")
    print(f"  {launcher} add mistake --date ... --context ... --mistake ... --fix ...")
    print(fmt_dim("  Or, in a shell:  export ENGRAM_DB_PATH=" + db))
    print()
    print(fmt_bold("Point an agent's hooks at this brain (Claude Code):"))
    print(fmt_dim(f'  UserPromptSubmit → "{launcher} hook recall"'))
    print(fmt_dim(f'  PreToolUse (Edit|Write|Bash) → "{launcher} hook guard"'))


def cmd_brain_list(args):
    _ = args
    root = brains_root()
    if not os.path.isdir(root):
        print(fmt_dim("No brains yet. Create one: engram brain new <name>"))
        return
    names = sorted(
        d for d in os.listdir(root)
        if os.path.isfile(os.path.join(root, d, "memory.db"))
    )
    if not names:
        print(fmt_dim("No brains yet. Create one: engram brain new <name>"))
        return
    print(fmt_header(f"Brains ({len(names)}):"))
    for name in names:
        db = _brain_db(name)
        counts = {}
        try:
            with get_connection(db) as conn:
                for label, table in (("m", "mistakes"), ("p", "patterns"), ("s", "skills")):
                    counts[label] = conn.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
            summary = f"{counts['m']} mistakes, {counts['p']} patterns, {counts['s']} skills"
        except Exception:
            summary = "(unreadable)"
        size_kb = os.path.getsize(db) // 1024
        print(f"  {fmt_bold(name):<28} {summary}  {fmt_dim(f'[{size_kb} KB]')}")


def cmd_brain_path(args):
    db = _brain_db(args.name)
    if not os.path.isfile(db):
        print(f"No brain '{args.name}'. Create it: engram brain new {args.name}")
        sys.exit(1)
    print(db)
